/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Channels
         * @description The services found by the most recent completed television scan.
         */
        get: operations["channels_api_v1_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Devices
         * @description Every receiver and tuner that can currently be opened.
         */
        get: operations["devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Favourites
         * @description Every remembered station and channel, in frequency order.
         *
         *     Kept by the server rather than the browser: a receiver is a thing in a room, reached
         *     from a laptop, a phone and a television, and a list held in one browser's storage is
         *     invisible to the other two.
         */
        get: operations["list_favourites_api_v1_favourites_get"];
        put?: never;
        /**
         * Add Favourite
         * @description Remember a station or channel.
         *
         *     Adding something already remembered replaces it, so a renamed station keeps its place
         *     rather than appearing twice.
         */
        post: operations["add_favourite_api_v1_favourites_post"];
        /**
         * Remove Favourite
         * @description Forget a station or channel.
         *
         *     Forgetting something that was not remembered is not an error: a client that sends the
         *     same request twice, or that is out of step with another client, should end up with the
         *     state it asked for rather than an error to handle.
         */
        delete: operations["remove_favourite_api_v1_favourites_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description What this installation can do.
         *
         *     Worth asking before offering a button that cannot work: playback needs libVLC, and a
         *     scan needs a receiver.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description Every remembered scan, newest first.
         */
        get: operations["list_scans_api_v1_scans_get"];
        put?: never;
        /**
         * Start Scan
         * @description Start a scan.
         *
         *     Returns at once with an identifier. The scan itself runs in the background, because an
         *     FM sweep takes seconds and a television sweep up to a minute.
         */
        post: operations["start_scan_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Detail
         * @description One scan, with its results once it has finished.
         */
        get: operations["scan_detail_api_v1_scans__scan_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Scan
         * @description Ask a scan to stop.
         *
         *     A scan in progress finishes the segment it is on rather than being killed: a receiver
         *     abandoned mid-read leaves a mess for the next caller.
         */
        delete: operations["cancel_scan_api_v1_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spectrum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spectrum Status
         * @description How the spectrum feed is configured, and whether anybody is watching.
         */
        get: operations["spectrum_status_api_v1_spectrum_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stations
         * @description The stations found by the most recent completed FM scan.
         *
         *     Empty until one has run, which is different from a scan that found nothing -- the scan
         *     list says which.
         */
        get: operations["stations_api_v1_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Status
         * @description What is being streamed, if anything.
         */
        get: operations["stream_status_api_v1_streams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/fm/{freq_hz}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Fm
         * @description Play an FM station as a WAV stream.
         *
         *     The frontend does not decode radio: it points a player at this URL. Anything that
         *     understands WAV over HTTP can play it, including libVLC and a browser.
         *
         *     Args:
         *         freq_hz: The station to tune.
         *         seconds: Stop after this much audio, giving a finite clip. Without it the stream
         *             runs until the client goes away, which is what live listening wants.
         */
        get: operations["stream_fm_api_v1_streams_fm__freq_hz__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Band
         * @description Which band a scan covers.
         * @enum {string}
         */
        Band: "fm" | "tv";
        /**
         * Capabilities
         * @description What this installation can actually do.
         *
         *     Worth asking before offering a button that cannot work: playback needs libVLC, the RTL-SDR
         *     driver needs its optional extra, and a scan needs a receiver.
         */
        Capabilities: {
            /**
             * Libvlc Version
             * @description libVLC version, if present
             */
            libvlc_version?: string | null;
            /**
             * Playback
             * @description Whether audio can be played, which needs libVLC
             */
            playback: boolean;
            /**
             * Receivers
             * @description How many IQ receivers were found
             */
            receivers: number;
            /**
             * Rtlsdr
             * @description Whether the RTL-SDR driver's dependency is installed
             */
            rtlsdr: boolean;
            /**
             * Tuners
             * @description How many DVB tuners were found
             */
            tuners: number;
            /**
             * Version
             * @description OpenWave version
             */
            version: string;
        };
        /**
         * Channel
         * @description One digital television or radio service, as found by a scan.
         */
        Channel: {
            /**
             * Audio Pid
             * @description PID of the first audio stream
             */
            audio_pid?: number | null;
            /**
             * Logical Channel
             * @description The number a viewer types. Published by the network in a private descriptor rather than by the standard, so plenty of multiplexes do not carry it.
             */
            logical_channel?: number | null;
            /**
             * Mux Freq Hz
             * @description Centre frequency of the multiplex carrying this service
             */
            mux_freq_hz: number;
            /**
             * Name
             * @description What the service is called, from the Service Description Table
             */
            name: string;
            /**
             * Provider
             * @description Who runs the service
             */
            provider?: string | null;
            /**
             * Running
             * @description Whether the service is on the air now
             * @default true
             */
            running: boolean;
            /**
             * Scrambled
             * @description Whether access is controlled. OpenWave reports this and goes no further: see docs/legal.md.
             * @default false
             */
            scrambled: boolean;
            /**
             * Service Id
             * @description Identifier within the multiplex, which is also its programme number
             */
            service_id: number;
            /**
             * Service Type
             * @description Service type from EN 300 468. Kept as a number because the list is long, country-specific in places, and still growing.
             */
            service_type: number;
            /**
             * Snr Db
             * @description Carrier-to-noise ratio the tuner reported for the multiplex
             */
            snr_db?: number | null;
            /**
             * Strength Dbm
             * @description Signal strength the tuner reported, where it provides one
             */
            strength_dbm?: number | null;
            /**
             * Transport Stream Id
             * @description Identifier of the multiplex carrying this service
             */
            transport_stream_id: number;
            /**
             * Video Pid
             * @description PID of the video stream, if there is one
             */
            video_pid?: number | null;
        };
        /**
         * DeviceSummary
         * @description One receiver or tuner, as a device picker needs it.
         */
        DeviceSummary: {
            /** Driver */
            driver: string;
            /** Index */
            index: number;
            /**
             * Kind
             * @description Whether this produces IQ samples or a demodulated transport stream
             * @enum {string}
             */
            kind: "receiver" | "tuner";
            /** Label */
            label: string;
            /** Serial */
            serial?: string | null;
            /**
             * Spec
             * @description What to pass as the device, such as 'rtlsdr:1'
             */
            spec: string;
            /**
             * Validated On Hardware
             * @description Whether this driver has ever been run against the hardware it targets. False for the real receivers: the maintainer owns none, so they are written from the vendor interfaces and unverified. A client should say so rather than imply otherwise.
             */
            validated_on_hardware: boolean;
        };
        /**
         * Favourite
         * @description One remembered station or channel.
         */
        Favourite: {
            /**
             * Added At
             * Format: date-time
             * @description When it was added
             */
            added_at?: string;
            /**
             * Freq Hz
             * @description For a station, its carrier; for a channel, the frequency of the multiplex carrying it.
             */
            freq_hz: number;
            kind: components["schemas"]["FavouriteKind"];
            /**
             * Name
             * @description What to call it in a list
             */
            name: string;
            /**
             * Service Id
             * @description Which service within a multiplex, for a television channel
             */
            service_id?: number | null;
        };
        /**
         * FavouriteKind
         * @description What kind of thing has been marked as a favourite.
         * @enum {string}
         */
        FavouriteKind: "station" | "channel";
        /**
         * FmScanResults
         * @description What an FM scan found.
         */
        FmScanResults: {
            /** Channels Measured */
            channels_measured: number;
            /** Complete */
            complete: boolean;
            /**
             * Coverage
             * @description Fraction of the band the receiver could reach. Below one when replaying a capture, which holds a single window of spectrum.
             */
            coverage: number;
            /** Plan */
            plan: string;
            /** Sample Rate Hz */
            sample_rate_hz: number;
            /**
             * Stations
             * @default []
             */
            stations: components["schemas"]["Station"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MultiplexSummary
         * @description One multiplex a television scan locked onto.
         */
        MultiplexSummary: {
            /** Bandwidth Hz */
            bandwidth_hz: number;
            /**
             * Channel
             * @description Channel number on the plan scanned
             */
            channel?: number | null;
            /** Freq Hz */
            freq_hz: number;
            /** Network Name */
            network_name?: string | null;
            /** Services */
            services: number;
            /** Snr Db */
            snr_db?: number | null;
            /** Transport Stream Id */
            transport_stream_id?: number | null;
        };
        /**
         * ScanDetail
         * @description A scan with its results.
         */
        ScanDetail: {
            band: components["schemas"]["Band"];
            /**
             * Error
             * @description Why the scan failed, when it did
             */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            fm?: components["schemas"]["FmScanResults"] | null;
            /** Id */
            id: string;
            progress?: components["schemas"]["ScanProgress"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            state: components["schemas"]["ScanState"];
            tv?: components["schemas"]["TvScanResults"] | null;
        };
        /**
         * ScanProgress
         * @description How far a scan has got.
         */
        ScanProgress: {
            /**
             * Done
             * @description Steps completed
             */
            done: number;
            /**
             * Frequency Hz
             * @description Where the receiver is at this moment
             */
            frequency_hz?: number | null;
            /**
             * Stage
             * @description What the scan is doing, in words a person can read
             */
            stage: string;
            /**
             * Total
             * @description Steps in this stage, or zero if not yet known
             */
            total: number;
        };
        /**
         * ScanRequest
         * @description What to scan, and how thoroughly.
         */
        ScanRequest: {
            /**
             * @description Which band to sweep
             * @default fm
             */
            band: components["schemas"]["Band"];
            /**
             * Device
             * @description Receiver or tuner to use. Defaults to whatever the server was started with.
             */
            device?: string | null;
            /**
             * Identify
             * @description Whether to demodulate each FM station to decide stereo
             * @default true
             */
            identify: boolean;
            /**
             * Include Scrambled
             * @description Whether to list television services that are encrypted
             * @default true
             */
            include_scrambled: boolean;
            /**
             * Lock Timeout S
             * @description Seconds to give a DVB demodulator to lock onto each channel
             */
            lock_timeout_s?: number | null;
            /**
             * Plan
             * @description Band plan: 'fm' or 'fm-japan' for radio, 'uhf' or 'vhf' for television
             */
            plan?: string | null;
            /**
             * Rds
             * @description Whether to read RDS, which is what fills in station names. It needs about a second of signal per station and so dominates how long a scan takes.
             * @default true
             */
            rds: boolean;
            /**
             * Sample Rate Hz
             * @description Sample rate for an FM scan
             */
            sample_rate_hz?: number | null;
            /**
             * Threshold Db
             * @description Signal-to-noise ratio for an FM channel to count as occupied
             */
            threshold_db?: number | null;
        };
        /**
         * ScanState
         * @description Where a scan has got to.
         *
         *     A scan takes seconds for FM and up to a minute for television, which is far too long for an
         *     HTTP request to wait on. So a scan is a job: it is started, it progresses, and its result is
         *     collected afterwards.
         * @enum {string}
         */
        ScanState: "pending" | "running" | "complete" | "failed" | "cancelled";
        /**
         * ScanSummary
         * @description A scan without its results, for a listing.
         */
        ScanSummary: {
            band: components["schemas"]["Band"];
            /**
             * Error
             * @description Why the scan failed, when it did
             */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            progress?: components["schemas"]["ScanProgress"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            state: components["schemas"]["ScanState"];
        };
        /**
         * Station
         * @description One FM broadcast station, as found by a scan.
         *
         *     Levels are in dBFS, relative to full scale. A consumer SDR has no calibrated power
         *     reference, so comparisons between stations and signal-to-noise ratios are meaningful while
         *     absolute power is not. See :mod:`openwave.core.units`.
         */
        Station: {
            /**
             * Bandwidth Hz
             * @description Channel bandwidth the power was measured over
             */
            bandwidth_hz: number;
            /**
             * Freq Hz
             * @description Carrier frequency in hertz
             */
            freq_hz: number;
            /**
             * Name
             * @description Station name, from the RDS programme service field.
             */
            name?: string | null;
            /**
             * Pi
             * @description RDS programme identification: a 16-bit code identifying the station within its country. Transmitters carrying the same programme share it, which is how a receiver follows a station across frequencies.
             */
            pi?: number | null;
            /**
             * Pilot Level Db
             * @description How far the 19 kHz pilot stood above the multiplex around it, when checked
             */
            pilot_level_db?: number | null;
            /**
             * Power Dbfs
             * @description Channel power relative to full scale
             */
            power_dbfs: number;
            /**
             * Pty
             * @description RDS programme type, as the raw five-bit number. Europe and North America assign the same bits to different genres, so the number is kept rather than a label.
             */
            pty?: number | null;
            /**
             * Radio Text
             * @description RDS RadioText: a longer free-text field, often the programme or track.
             */
            radio_text?: string | null;
            /**
             * Snr Db
             * @description How far the channel stands above the noise floor
             */
            snr_db: number;
            /**
             * Stereo
             * @description Whether a stereo pilot was found. None means it was not checked: a band scan measures power only, and deciding stereo needs the station demodulated.
             */
            stereo?: boolean | null;
        };
        /**
         * TvScanResults
         * @description What a television scan found.
         */
        TvScanResults: {
            /**
             * Channels
             * @default []
             */
            channels: components["schemas"]["Channel"][];
            /** Channels Tried */
            channels_tried: number;
            /**
             * Incomplete
             * @description Frequencies that locked but whose tables never arrived. Reported separately because the signal being present and unreadable usually means marginal reception.
             * @default []
             */
            incomplete: number[];
            /**
             * Multiplexes
             * @default []
             */
            multiplexes: components["schemas"]["MultiplexSummary"][];
            /** Plan */
            plan: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    channels_api_v1_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
        };
    };
    devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSummary"][];
                };
            };
        };
    };
    list_favourites_api_v1_favourites_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["FavouriteKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favourite"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favourite_api_v1_favourites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Favourite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favourite"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favourite_api_v1_favourites_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Favourite"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    list_scans_api_v1_scans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"][];
                };
            };
        };
    };
    start_scan_api_v1_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_detail_api_v1_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_v1_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spectrum_status_api_v1_spectrum_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    stations_api_v1_stations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Station"][];
                };
            };
        };
    };
    stream_status_api_v1_streams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    stream_fm_api_v1_streams_fm__freq_hz__get: {
        parameters: {
            query?: {
                seconds?: number | null;
            };
            header?: never;
            path: {
                freq_hz: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
